/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.desafio2.mediateca;

/**
 *
 * @author Fab
 */
public class menuadmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuadmin
     */
    public menuadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu1.setText("Menu");

        jMenu3.setText("Agregar Material");

        jMenu9.setText("Material Escrito");

        jMenuItem1.setText("Libro");
        jMenu9.add(jMenuItem1);

        jMenuItem2.setText("Revistas");
        jMenu9.add(jMenuItem2);

        jMenu3.add(jMenu9);

        jMenu10.setText("Material Audiovisual");

        jMenuItem3.setText("CD De Audio");
        jMenu10.add(jMenuItem3);

        jMenuItem4.setText("DVD");
        jMenu10.add(jMenuItem4);

        jMenu3.add(jMenu10);

        jMenu1.add(jMenu3);

        jMenu4.setText("Modificar Material");

        jMenu8.setText("Material Escrito");

        jMenuItem5.setText("Libro");
        jMenu8.add(jMenuItem5);

        jMenuItem6.setText("Revista");
        jMenu8.add(jMenuItem6);

        jMenu4.add(jMenu8);

        jMenu11.setText("Material Audiovisual");

        jMenuItem7.setText("CD de Audio");
        jMenu11.add(jMenuItem7);

        jMenuItem8.setText("DVD");
        jMenu11.add(jMenuItem8);

        jMenu4.add(jMenu11);

        jMenu1.add(jMenu4);

        jMenu5.setText("Listar Materiales Disponibles");

        jMenu12.setText("Material Escrito");

        jMenuItem9.setText("Libro");
        jMenu12.add(jMenuItem9);

        jMenuItem10.setText("Revista");
        jMenu12.add(jMenuItem10);

        jMenu5.add(jMenu12);

        jMenu13.setText("Material Audiovisual");

        jMenuItem11.setText("CD de Audio");
        jMenu13.add(jMenuItem11);

        jMenuItem12.setText("DVD");
        jMenu13.add(jMenuItem12);

        jMenu5.add(jMenu13);

        jMenu1.add(jMenu5);

        jMenu6.setText("Borrar Materiales");

        jMenu14.setText("Material Escrito");

        jMenuItem13.setText("Libro");
        jMenu14.add(jMenuItem13);

        jMenuItem14.setText("Revista");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem14);

        jMenu6.add(jMenu14);

        jMenu15.setText("Material Audiovisual");

        jMenuItem15.setText("CD de Audio");
        jMenu15.add(jMenuItem15);

        jMenuItem16.setText("DVD");
        jMenu15.add(jMenuItem16);

        jMenu6.add(jMenu15);

        jMenu1.add(jMenu6);

        jMenu7.setText("Buscar Material");

        jMenu16.setText("Material Escrito");

        jMenuItem17.setText("Libro");
        jMenu16.add(jMenuItem17);

        jMenuItem18.setText("Revista");
        jMenu16.add(jMenuItem18);

        jMenu7.add(jMenu16);

        jMenu17.setText("Material Audiovisual");

        jMenuItem19.setText("CD de Audio");
        jMenu17.add(jMenuItem19);

        jMenuItem20.setText("DVD");
        jMenu17.add(jMenuItem20);

        jMenu7.add(jMenu17);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
